import Yape from './yape.png'
import Plin from './plin.png'
import Mastercard from './mastercard.svg'
import Visa from './visa.svg'
import Cusco from './cusco.png'
import Colores from './7-colores.png'
import Logo from './logo.png'
import Ica from './Ica.jpg'
import Selva from './selva.jfif'
export { Yape, Plin, Mastercard, Visa, Cusco, Colores, Logo ,Ica ,Selva}
